version: '3.8'

services:
  app:
    image: gulseminsevindi/cloud-storage
      #build: context:  . #bu klasördeki dockerfile' ı kullanarak imageı build et diyor ama biz artık dockerhubdan build edilmiş image i alıyoruz. onda aşağıdakini yazdık

    ports:
      - "8082:8080"
    depends_on:
      - db
    # Konteyner çalıştığında bu değişkenlerin tekrar ayarlanması gerekmez,
    # çünkü zaten imajın içine ENV olarak gömüldüler.

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: cloud-storage-db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: